services:
  # Сервис 1: База данных PostgreSQL
  borda-db:
    image: postgres:15-alpine
    container_name: borda_postgres
    environment:
      POSTGRES_DB: borda_db
      POSTGRES_USER: borda_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5435:5432"
    volumes:
      - borda_data:/var/lib/postgresql/data

  # Сервис 2: Redis
  borda-redis:
    image: redis:7-alpine
    container_name: borda_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  # Сервис 3: Приложение
  borda-app:
    build: . # собрать образ из докерфайла
    container_name: borda_app
    ports:
      - "8080:8080"
    environment:
      # явно указать SPRING, что он в докере
      - SPRING_PROFILES_ACTIVE=docker
      - TZ=Europe/Moscow
    command: [ "java", "-Duser.timezone=Europe/Moscow", "-jar", "app.jar" ] # иначе таймштампы по гринвичу летят
    depends_on:
      - borda-db
      - borda-redis
    volumes:
      - ./uploads:/app/uploads

volumes:
  borda_data: