spring:
  application:
    name: borda-service
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB     # Максимальный размер одного файла
      max-request-size: 10MB  # Максимальный размер всего запроса