spring:
  application:
    name: borda-service
  datasource:
    url: jdbc:postgresql://localhost:5435/borda_db
    username: borda_user
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB     # Максимальный размер одного файла
      max-request-size: 10MB  # Максимальный размер всего запроса